spring.application.name=Architect

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/llmDataDb
spring.datasource.username=root
spring.datasource.password=123456

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Custom Properties
rabbitmq.exchange=user.exchange
rabbitmq.queue=user.queue
rabbitmq.routing-key=user.routing.key
rabbitmq.dlq=user.dlq